In [57]:
import pandas as pd
import numpy as np

In [58]:
df = pd.read_csv(r"../data/airline_cleaned.csv")

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87273 entries, 0 to 87272
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Flight_Number      87273 non-null  int64
 1   Airline            87273 non-null  object
 2   Aircraft_Type      87273 non-null  object
 3   Origin             87273 non-null  object
 4   Destination        87273 non-null  object
 5   Date               87273 non-null  object
 6   Distance_km        87273 non-null  float64
 7   Duration_hours     83820 non-null  float64
 8   Ticket_Price       82967 non-null  float64
 9   Fuel_Cost          84675 non-null  float64
 10  Weather_Condition  87273 non-null  object
 11  Delay_minutes      85558 non-null  float64
 12  Passenger_Count    87273 non-null  int64
 13  Fuel_cost_per_km   84675 non-null  float64
 14  Price_per_hour     79677 non-null  float64
 15  Delayed_Flag       87273 non-null  bool
 16  Month              87273 non-null  int64
 17  Day                87273 non-null  int64
 18  Route              87273 non-null  object
dtypes: bool(1), float64(7), int64(4), object(7)
memory usage: 12.1+ MB

In [60]:
df.describe()

,Flight_Number,Distance_km,Duration_hours,Ticket_Price,Fuel_Cost,Delay_minutes,Passenger_Count,Fuel_cost_per_km,Price_per_hour,Month,Day
count,87273.000000,87273.000000,83820.000000,82967.000000,84675.000000,85558.000000,87273.000000,84675.000000,79677.000000,87273.000000,87273.000000
mean,5500.005523,1050.582838,1.894933,3423.845861,3744.374730,22.470611,148.512896,3.579903,2140.851476,6.532444,15.658680
std,2601.170281,482.822944,0.753913,666.861268,1794.142291,20.052077,71.795491,0.459965,1062.833730,3.446596,8.775973
min,1000.000000,124.000000,0.500000,1715.010897,500.000000,0.000000,31.000000,2.325621,502.378857,1.000000,1.000000
25%,3244.000000,529.000000,1.316330,2914.767260,2160.940470,6.024825,108.000000,3.469616,1410.938836,4.000000,8.000000
50%,5505.000000,1056.000000,1.863438,3341.778635,3701.726900,18.898850,142.000000,3.608831,1878.647453,7.000000,16.000000
75%,7748.000000,1395.000000,2.374798,3895.731031,5030.494148,33.401470,182.000000,3.775141,2600.424491,10.000000,23.000000
max,9998.000000,1769.000000,4.349843,5612.914951,7575.644450,125.612276,332.000000,5.428176,9873.192858,12.000000,31.000000

In [61]:
df["Airline"].nunique()

5

In [62]:
df["Date"].min(),df["Date"].max()

('2023-01-01', '2023-12-31')

In [63]:
df.isna().sum()

Flight_Number           0
Airline                 0
Aircraft_Type           0
Origin                  0
Destination             0
Date                    0
Distance_km             0
Duration_hours       3453
Ticket_Price         4306
Fuel_Cost            2598
Weather_Condition       0
Delay_minutes        1715
Passenger_Count         0
Fuel_cost_per_km     2598
Price_per_hour       7596
Delayed_Flag            0
Month                   0
Day                     0
Route                   0
dtype: int64

In [64]:
df["Duration_hours"].isna().sum()

np.int64(3453)

In [65]:
df[df["Airline"]=="IndiGo"]

,Flight_Number,Airline,Aircraft_Type,Origin,Destination,Date,Distance_km,Duration_hours,Ticket_Price,Fuel_Cost,Weather_Condition,Delay_minutes,Passenger_Count,Fuel_cost_per_km,Price_per_hour,Delayed_Flag,Month,Day,Route
1,5263,IndiGo,A320,AMD,PNQ,2023-09-21,519.0,NaN,2912.486246,1790.502002,Cloudy,27.908655,119,3.449908,NaN,True,9,21,AMD→PNQ
6,7670,IndiGo,B777,CCU,BLR,2023-02-02,1601.0,2.179993,4062.407214,6760.325458,Clear,16.373260,312,4.222564,1863.495553,True,2,2,CCU→BLR
7,4562,IndiGo,B777,DEL,PNQ,2023-08-02,1186.0,1.839446,3556.615821,4978.035533,Clear,0.000000,279,4.197332,1933.525866,False,8,2,DEL→PNQ
13,8434,IndiGo,B737,MAA,HYD,2023-08-22,516.0,1.013932,2924.485528,1879.675483,Foggy,72.198642,101,3.642782,2884.301931,True,8,22,MAA→HYD
15,6150,IndiGo,B737,AMD,HYD,2023-12-09,907.0,1.489524,3004.930797,3278.565090,Foggy,70.127106,116,3.614735,2017.376019,True,12,9,AMD→HYD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87248,1115,IndiGo,A321,PNQ,DEL,2023-09-22,1186.0,1.927063,3509.262700,4329.267938,Clear,23.066712,160,3.650310,1821.041993,True,9,22,PNQ→DEL
87256,5943,IndiGo,A320,PNQ,AMD,2023-04-04,519.0,1.136974,3602.765539,1835.596510,Clear,0.000000,130,3.536795,3168.732246,False,4,4,PNQ→AMD
87261,6401,IndiGo,A320,DEL,HYD,2023-07-27,1265.0,2.155620,3211.179205,4346.264783,Cloudy,0.424279,133,3.435782,1489.677554,False,7,27,DEL→HYD
87267,5006,IndiGo,ATR72,PNQ,AMD,2023-10-29,519.0,1.557797,3037.316965,1463.911320,Clear,20.466009,54,2.820638,1949.751925,True,10,29,PNQ→AMD
87271,2248,IndiGo,B777,MAA,PNQ,2023-07-17,933.0,1.425115,3542.425616,3908.780885,Rainy,27.970932,243,4.189476,2485.712197,True,7,17,MAA→PNQ

In [66]:
df[df["Delay_minutes"]>30]

,Flight_Number,Airline,Aircraft_Type,Origin,Destination,Date,Distance_km,Duration_hours,Ticket_Price,Fuel_Cost,Weather_Condition,Delay_minutes,Passenger_Count,Fuel_cost_per_km,Price_per_hour,Delayed_Flag,Month,Day,Route
11,9397,Air India,A320,DEL,CCU,2023-03-15,1423.0,2.131190,3756.982406,4989.393836,Rainy,46.930670,123,3.506250,1762.856345,True,3,15,DEL→CCU
12,1289,Vistara,B777,CCU,PNQ,2023-04-21,1671.0,NaN,4959.089625,7032.822873,Rainy,61.485096,326,4.208751,NaN,True,4,21,CCU→PNQ
13,8434,IndiGo,B737,MAA,HYD,2023-08-22,516.0,1.013932,2924.485528,1879.675483,Foggy,72.198642,101,3.642782,2884.301931,True,8,22,MAA→HYD
15,6150,IndiGo,B737,AMD,HYD,2023-12-09,907.0,1.489524,3004.930797,3278.565090,Foggy,70.127106,116,3.614735,2017.376019,True,12,9,AMD→HYD
23,4201,SpiceJet,B777,MAA,DEL,2023-02-09,1769.0,2.558762,3400.113758,7520.967289,Rainy,34.438852,288,4.251536,1328.811823,True,2,9,MAA→DEL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87244,9389,Air India,A321,BOM,CCU,2023-09-16,1762.0,2.546624,4010.483925,6431.458708,Rainy,43.911688,147,3.650090,1574.823633,True,9,16,BOM→CCU
87253,1490,SpiceJet,A321,CCU,DEL,2023-08-30,1423.0,2.138809,3402.426255,5260.502867,Rainy,67.617864,174,3.696769,1590.804296,True,8,30,CCU→DEL
87264,7744,Air India,B737,PNQ,BOM,2023-03-08,124.0,0.618771,3361.177557,500.000000,Foggy,91.946013,90,4.032258,5432.021082,True,3,8,PNQ→BOM
87268,5730,GoAir,ATR72,MAA,AMD,2023-08-01,1395.0,3.140030,2322.841620,3849.760336,Foggy,38.650092,57,2.759685,739.751444,True,8,1,MAA→AMD
87272,6529,SpiceJet,ATR72,BOM,MAA,2023-05-23,1056.0,2.655092,2963.984721,2977.489964,Foggy,88.251829,65,2.819593,1116.339561,True,5,23,BOM→MAA

In [67]:
df[(df["Origin"]=="CCU") & (df["Destination"]=="DEL")]

,Flight_Number,Airline,Aircraft_Type,Origin,Destination,Date,Distance_km,Duration_hours,Ticket_Price,Fuel_Cost,Weather_Condition,Delay_minutes,Passenger_Count,Fuel_cost_per_km,Price_per_hour,Delayed_Flag,Month,Day,Route
2,1877,GoAir,B737,CCU,DEL,2023-11-30,1423.0,2.112585,2177.869901,5122.704201,Cloudy,26.339672,122,3.599933,1030.902631,True,11,30,CCU→DEL
42,8414,Vistara,B777,CCU,DEL,2023-04-25,1423.0,2.133566,4458.971562,6011.897744,Cloudy,14.939082,293,4.224805,2089.914589,False,4,25,CCU→DEL
136,7874,Air India,ATR72,CCU,DEL,2023-09-30,1423.0,3.429172,NaN,4022.767910,Cloudy,30.850021,61,2.826963,NaN,True,9,30,CCU→DEL
159,8241,SpiceJet,A321,CCU,DEL,2023-01-09,1423.0,2.104854,3353.188702,5287.891612,Rainy,30.756457,202,3.716017,1593.073967,True,1,9,CCU→DEL
208,8748,SpiceJet,B777,CCU,DEL,2023-01-21,1423.0,2.006453,3212.239686,5986.133874,Foggy,61.296507,313,4.206700,1600.954077,True,1,21,CCU→DEL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86799,9049,IndiGo,B737,CCU,DEL,2023-07-23,1423.0,2.203213,3005.944641,5168.226069,Clear,17.443837,129,3.631923,1364.345869,True,7,23,CCU→DEL
86816,1760,Vistara,B777,CCU,DEL,2023-09-26,1423.0,2.189798,4681.121673,5952.866734,Cloudy,10.140649,288,4.183322,2137.695698,False,9,26,CCU→DEL
87144,4093,IndiGo,B737,CCU,DEL,2023-05-29,1423.0,2.198820,3463.674864,5066.296459,Cloudy,6.674605,163,3.560293,1575.242904,False,5,29,CCU→DEL
87253,1490,SpiceJet,A321,CCU,DEL,2023-08-30,1423.0,2.138809,3402.426255,5260.502867,Rainy,67.617864,174,3.696769,1590.804296,True,8,30,CCU→DEL
87257,8022,Air India,B737,CCU,DEL,2023-03-23,1423.0,2.256574,3595.856423,5107.469995,Clear,7.076558,165,3.589227,1593.502589,False,3,23,CCU→DEL

In [68]:
df[df["Delay_minutes"]==0]

,Flight_Number,Airline,Aircraft_Type,Origin,Destination,Date,Distance_km,Duration_hours,Ticket_Price,Fuel_Cost,Weather_Condition,Delay_minutes,Passenger_Count,Fuel_cost_per_km,Price_per_hour,Delayed_Flag,Month,Day,Route
0,8498,SpiceJet,ATR72,CCU,MAA,2023-06-12,1384.0,3.094867,2963.516704,3828.490167,Cloudy,0.0,62,2.766250,957.558735,False,6,12,CCU→MAA
7,4562,IndiGo,B777,DEL,PNQ,2023-08-02,1186.0,1.839446,3556.615821,4978.035533,Clear,0.0,279,4.197332,1933.525866,False,8,2,DEL→PNQ
9,1612,Air India,B777,HYD,BOM,2023-02-10,650.0,1.124882,3898.783497,2748.086239,Clear,0.0,275,4.227825,3465.947389,False,2,10,HYD→BOM
19,8807,SpiceJet,A321,HYD,BLR,2023-02-16,499.0,1.075818,3158.182042,1865.320805,Clear,0.0,152,3.738118,2935.610320,False,2,16,HYD→BLR
20,9399,IndiGo,A321,MAA,BLR,2023-05-09,297.0,0.826798,3470.151406,1111.509579,Clear,0.0,151,3.742456,4197.099258,False,5,9,MAA→BLR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87250,4501,SpiceJet,A320,MAA,BLR,2023-12-26,297.0,0.743091,2782.627673,1040.828037,Cloudy,0.0,92,3.504472,3744.663720,False,12,26,MAA→BLR
87255,8663,GoAir,ATR72,BOM,MAA,2023-09-07,1056.0,2.588687,2310.403332,3017.215723,Clear,0.0,58,2.857212,892.500087,False,9,7,BOM→MAA
87256,5943,IndiGo,A320,PNQ,AMD,2023-04-04,519.0,1.136974,3602.765539,1835.596510,Clear,0.0,130,3.536795,3168.732246,False,4,4,PNQ→AMD
87259,1751,GoAir,B777,PNQ,BLR,2023-10-14,742.0,1.256462,3095.667634,NaN,Cloudy,0.0,236,NaN,2463.796927,False,10,14,PNQ→BLR
87266,5880,GoAir,A321,BOM,BLR,2023-06-17,856.0,1.408556,2905.163118,3218.775649,Cloudy,0.0,156,3.760252,2062.511170,False,6,17,BOM→BLR

In [69]:
avg = df["Ticket_Price"].mean()
df[df["Ticket_Price"]>avg]

,Flight_Number,Airline,Aircraft_Type,Origin,Destination,Date,Distance_km,Duration_hours,Ticket_Price,Fuel_Cost,Weather_Condition,Delay_minutes,Passenger_Count,Fuel_cost_per_km,Price_per_hour,Delayed_Flag,Month,Day,Route
6,7670,IndiGo,B777,CCU,BLR,2023-02-02,1601.0,2.179993,4062.407214,6760.325458,Clear,16.373260,312,4.222564,1863.495553,True,2,2,CCU→BLR
7,4562,IndiGo,B777,DEL,PNQ,2023-08-02,1186.0,1.839446,3556.615821,4978.035533,Clear,0.000000,279,4.197332,1933.525866,False,8,2,DEL→PNQ
9,1612,Air India,B777,HYD,BOM,2023-02-10,650.0,1.124882,3898.783497,2748.086239,Clear,0.000000,275,4.227825,3465.947389,False,2,10,HYD→BOM
10,8623,Air India,ATR72,AMD,MAA,2023-02-02,1395.0,3.092786,3688.119170,3964.885491,Cloudy,13.510211,47,2.842212,1192.490871,False,2,2,AMD→MAA
11,9397,Air India,A320,DEL,CCU,2023-03-15,1423.0,2.131190,3756.982406,4989.393836,Rainy,46.930670,123,3.506250,1762.856345,True,3,15,DEL→CCU
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87258,4639,Air India,B777,MAA,AMD,2023-03-25,1395.0,NaN,4040.416971,5800.302084,Clear,8.787268,255,4.157923,NaN,False,3,25,MAA→AMD
87260,7879,Air India,A321,DEL,BOM,2023-02-17,1167.0,1.813321,4171.571767,4308.313005,Rainy,21.385970,183,3.691785,2300.515370,True,2,17,DEL→BOM
87263,6877,Air India,A320,HYD,CCU,2023-02-06,1238.0,2.062949,3630.349613,4421.319605,Clear,12.916975,146,3.571341,1759.786599,False,2,6,HYD→CCU
87265,5721,Air India,ATR72,DEL,AMD,2023-07-05,806.0,2.069812,3430.663306,2152.472051,Clear,16.613167,53,2.670561,1657.475784,True,7,5,DEL→AMD
87271,2248,IndiGo,B777,MAA,PNQ,2023-07-17,933.0,1.425115,3542.425616,3908.780885,Rainy,27.970932,243,4.189476,2485.712197,True,7,17,MAA→PNQ

In [70]:
df["Date"] = pd.to_datetime(df["Date"],errors = 'coerce')
#necessary

In [71]:
df[
    (df["Date"].dt.year == 2023) & 
    (df["Date"].dt.month == 10)
    ]

,Flight_Number,Airline,Aircraft_Type,Origin,Destination,Date,Distance_km,Duration_hours,Ticket_Price,Fuel_Cost,Weather_Condition,Delay_minutes,Passenger_Count,Fuel_cost_per_km,Price_per_hour,Delayed_Flag,Month,Day,Route
4,2722,GoAir,ATR72,HYD,PNQ,2023-10-24,529.0,1.717573,2321.112931,1543.099700,Clear,18.920403,40,2.917013,1351.391047,True,10,24,HYD→PNQ
32,8423,GoAir,A321,CCU,MAA,2023-10-19,1384.0,2.067062,2948.938208,5090.346809,Clear,20.098305,206,3.677996,1426.633026,True,10,19,CCU→MAA
52,7325,SpiceJet,B777,BLR,PNQ,2023-10-22,742.0,1.337414,3498.253056,3164.742252,Rainy,30.845418,286,4.265151,2615.684236,True,10,22,BLR→PNQ
56,4311,GoAir,A320,HYD,AMD,2023-10-18,907.0,1.592604,2592.640766,3119.131445,Rainy,61.202588,156,3.438954,1627.925652,True,10,18,HYD→AMD
58,9400,IndiGo,B777,HYD,BOM,2023-10-13,650.0,1.121631,3455.060017,2762.225699,Cloudy,0.000000,205,4.249578,3080.390463,False,10,13,HYD→BOM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87196,6192,Air India,A320,BOM,PNQ,2023-10-16,124.0,0.669192,3260.223050,500.000000,Clear,21.374727,88,4.032258,4871.882169,True,10,16,BOM→PNQ
87218,1847,IndiGo,B737,MAA,AMD,2023-10-21,1395.0,2.181788,3146.479973,5112.461892,Rainy,62.460646,162,3.664847,1442.156819,True,10,21,MAA→AMD
87233,2605,Vistara,B737,HYD,BLR,2023-10-25,499.0,1.015347,3765.999506,1881.753239,Clear,7.759578,127,3.771049,3709.076793,False,10,25,HYD→BLR
87259,1751,GoAir,B777,PNQ,BLR,2023-10-14,742.0,1.256462,3095.667634,NaN,Cloudy,0.000000,236,NaN,2463.796927,False,10,14,PNQ→BLR
87267,5006,IndiGo,ATR72,PNQ,AMD,2023-10-29,519.0,1.557797,3037.316965,1463.911320,Clear,20.466009,54,2.820638,1949.751925,True,10,29,PNQ→AMD

In [72]:
df.groupby("Airline")["Ticket_Price"].mean()

Airline
Air India    3692.134847
GoAir        2685.758039
IndiGo       3357.643575
SpiceJet     3018.514859
Vistara      4367.481381
Name: Ticket_Price, dtype: float64

In [73]:
avg_delay = df.groupby("Airline")["Delay_minutes"].mean()
avg_delay.sort_values(ascending=False).head(1)

Airline
Vistara    22.641319
Name: Delay_minutes, dtype: float64

In [74]:
df.groupby("Aircraft_Type").size()

Aircraft_Type
A320     17516
A321     17327
ATR72    17473
B737     17408
B777     17549
dtype: int64

In [75]:
df.groupby("Airline")["Passenger_Count"].sum()

Airline
Air India    2607001
GoAir        2602203
IndiGo       2584844
SpiceJet     2564442
Vistara      2602676
Name: Passenger_Count, dtype: int64

In [76]:
df.groupby("Weather_Condition")["Delay_minutes"].sum()

Weather_Condition
Clear     550189.323582
Cloudy    540987.403333
Foggy     304221.825535
Rainy     527141.954867
Name: Delay_minutes, dtype: float64

In [77]:
max = df.groupby("Origin")["Airline"].max()
max.sort_values(ascending=False).head(1)

Origin
AMD    Vistara
Name: Airline, dtype: object

In [78]:

df.sort_values(by = "Ticket_Price",ascending= False).head(5)

,Flight_Number,Airline,Aircraft_Type,Origin,Destination,Date,Distance_km,Duration_hours,Ticket_Price,Fuel_Cost,Weather_Condition,Delay_minutes,Passenger_Count,Fuel_cost_per_km,Price_per_hour,Delayed_Flag,Month,Day,Route
73438,4372,Vistara,A321,BLR,DEL,2023-07-23,1747.0,2.616201,5612.914951,6531.996057,Foggy,91.340445,161,3.738979,2145.444518,True,7,23,BLR→DEL
84374,5817,Vistara,A321,DEL,MAA,2023-02-12,1769.0,2.618421,5560.949164,6444.241627,Cloudy,21.386968,152,3.642873,2123.779367,True,2,12,DEL→MAA
50037,8410,Vistara,B777,DEL,HYD,2023-06-23,1265.0,1.900558,5472.952449,5282.028105,Cloudy,42.376033,317,4.175516,2879.655841,True,6,23,DEL→HYD
14956,7611,Vistara,B777,HYD,DEL,2023-05-30,1265.0,NaN,5451.247796,5379.606508,Clear,19.608394,309,4.252653,NaN,True,5,30,HYD→DEL
46524,2931,Vistara,B777,BOM,CCU,2023-09-22,1762.0,NaN,5447.468186,7401.579033,Cloudy,35.427032,297,4.200669,NaN,True,9,22,BOM→CCU

In [79]:
df.sort_values(by="Distance_km",ascending=False).head(5)

,Flight_Number,Airline,Aircraft_Type,Origin,Destination,Date,Distance_km,Duration_hours,Ticket_Price,Fuel_Cost,Weather_Condition,Delay_minutes,Passenger_Count,Fuel_cost_per_km,Price_per_hour,Delayed_Flag,Month,Day,Route
87219,4795,GoAir,B777,MAA,DEL,2023-02-14,1769.0,2.498079,NaN,7441.380630,Rainy,52.933475,304,4.206546,NaN,True,2,14,MAA→DEL
87208,5359,Vistara,A320,DEL,MAA,2023-11-25,1769.0,2.513258,4365.768486,6162.328623,Clear,5.126209,159,3.483510,1737.095545,False,11,25,DEL→MAA
87204,3983,IndiGo,A321,DEL,MAA,2023-08-03,1769.0,2.703543,3944.784117,6550.334231,Foggy,70.439624,204,3.702846,1459.116608,True,8,3,DEL→MAA
46,9764,GoAir,B777,MAA,DEL,2023-03-19,1769.0,2.323040,2957.512869,7403.503421,Clear,14.489213,295,4.185135,1273.121877,False,3,19,MAA→DEL
43,9719,Vistara,A321,DEL,MAA,2023-06-10,1769.0,2.548761,4881.591768,6522.730396,Rainy,11.937943,202,3.687242,1915.280080,False,6,10,DEL→MAA

In [80]:
df.groupby("Airline")["Ticket_Price"].mean().sort_values(ascending = True)

Airline
GoAir        2685.758039
SpiceJet     3018.514859
IndiGo       3357.643575
Air India    3692.134847
Vistara      4367.481381
Name: Ticket_Price, dtype: float64

In [81]:
df.isnull()

,Flight_Number,Airline,Aircraft_Type,Origin,Destination,Date,Distance_km,Duration_hours,Ticket_Price,Fuel_Cost,Weather_Condition,Delay_minutes,Passenger_Count,Fuel_cost_per_km,Price_per_hour,Delayed_Flag,Month,Day,Route
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87268,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
87269,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
87270,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
87271,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
87272,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [82]:
df.dropna()

,Flight_Number,Airline,Aircraft_Type,Origin,Destination,Date,Distance_km,Duration_hours,Ticket_Price,Fuel_Cost,Weather_Condition,Delay_minutes,Passenger_Count,Fuel_cost_per_km,Price_per_hour,Delayed_Flag,Month,Day,Route
0,8498,SpiceJet,ATR72,CCU,MAA,2023-06-12,1384.0,3.094867,2963.516704,3828.490167,Cloudy,0.000000,62,2.766250,957.558735,False,6,12,CCU→MAA
2,1877,GoAir,B737,CCU,DEL,2023-11-30,1423.0,2.112585,2177.869901,5122.704201,Cloudy,26.339672,122,3.599933,1030.902631,True,11,30,CCU→DEL
3,1598,GoAir,B737,AMD,HYD,2023-06-30,907.0,1.515557,2204.381503,3289.369504,Cloudy,13.771963,143,3.626648,1454.502669,False,6,30,AMD→HYD
4,2722,GoAir,ATR72,HYD,PNQ,2023-10-24,529.0,1.717573,2321.112931,1543.099700,Clear,18.920403,40,2.917013,1351.391047,True,10,24,HYD→PNQ
6,7670,IndiGo,B777,CCU,BLR,2023-02-02,1601.0,2.179993,4062.407214,6760.325458,Clear,16.373260,312,4.222564,1863.495553,True,2,2,CCU→BLR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87268,5730,GoAir,ATR72,MAA,AMD,2023-08-01,1395.0,3.140030,2322.841620,3849.760336,Foggy,38.650092,57,2.759685,739.751444,True,8,1,MAA→AMD
87269,2098,GoAir,A321,CCU,AMD,2023-12-06,1753.0,2.531112,2995.180173,6435.115093,Clear,7.730974,195,3.670916,1183.345776,False,12,6,CCU→AMD
87270,1978,GoAir,A321,AMD,PNQ,2023-07-21,519.0,1.137145,2971.397586,2030.405612,Clear,3.564183,158,3.912150,2613.032172,False,7,21,AMD→PNQ
87271,2248,IndiGo,B777,MAA,PNQ,2023-07-17,933.0,1.425115,3542.425616,3908.780885,Rainy,27.970932,243,4.189476,2485.712197,True,7,17,MAA→PNQ
87272,6529,SpiceJet,ATR72,BOM,MAA,2023-05-23,1056.0,2.655092,2963.984721,2977.489964,Foggy,88.251829,65,2.819593,1116.339561,True,5,23,BOM→MAA

In [83]:
df["Fuel_cost_per_km"]= df["Fuel_Cost"]/df["Distance_km"]

In [84]:
df=df[df["Distance_km"]>0].copy()

In [85]:
df.groupby("Aircraft_Type")["Fuel_cost_per_km"].mean().sort_values(ascending= True)

Aircraft_Type
ATR72    2.846284
A320     3.519345
B737     3.617029
A321     3.712487
B777     4.203917
Name: Fuel_cost_per_km, dtype: float64

In [86]:
df.groupby("Airline")["Delay_minutes"].mean().sort_values().head(1)

Airline
SpiceJet    22.302662
Name: Delay_minutes, dtype: float64

In [87]:
df["Fuel_cost_per_km"]

0        2.766250
1        3.449908
2        3.599933
3        3.626648
4        2.917013
           ...
87268    2.759685
87269    3.670916
87270    3.912150
87271    4.189476
87272    2.819593
Name: Fuel_cost_per_km, Length: 87273, dtype: float64

In [88]:
df["Price_per_hour"]= df["Ticket_Price"]/df["Duration_hours"]

In [89]:
df["Price_per_hour"].replace([np.inf, -np.inf],np.nan)

0         957.558735
1                NaN
2        1030.902631
3        1454.502669
4        1351.391047
            ...
87268     739.751444
87269    1183.345776
87270    2613.032172
87271    2485.712197
87272    1116.339561
Name: Price_per_hour, Length: 87273, dtype: float64

In [90]:
df["Price_per_hour"].isna().sum()
df["Price_per_hour"].describe()

count    79677.000000
mean      2140.851476
std       1062.833730
min        502.378857
25%       1410.938836
50%       1878.647453
75%       2600.424491
max       9873.192858
Name: Price_per_hour, dtype: float64

In [91]:
df["Price_per_hour"].replace([np.inf, -np.inf],np.nan)

0         957.558735
1                NaN
2        1030.902631
3        1454.502669
4        1351.391047
            ...
87268     739.751444
87269    1183.345776
87270    2613.032172
87271    2485.712197
87272    1116.339561
Name: Price_per_hour, Length: 87273, dtype: float64

In [92]:
df["Delayed_Flag"] = (df["Delay_minutes"]>15)
df["Delayed_Flag"].astype(int)

0        0
1        1
2        1
3        0
4        1
        ..
87268    1
87269    0
87270    0
87271    1
87272    1
Name: Delayed_Flag, Length: 87273, dtype: int64

In [93]:
df["Month"]=df["Date"].dt.month
df["Day"]=df["Date"].dt.day

In [94]:
df[["Date","Month","Day"]]

            Date  Month  Day
0     2023-06-12      6   12
1     2023-09-21      9   21
2     2023-11-30     11   30
3     2023-06-30      6   30
4     2023-10-24     10   24
...          ...    ...  ...
87268 2023-08-01      8    1
87269 2023-12-06     12    6
87270 2023-07-21      7   21
87271 2023-07-17      7   17
87272 2023-05-23      5   23

[87273 rows x 3 columns]

In [95]:
df["Route"]= df["Origin"]+ "→" + df["Destination"]

In [96]:
df["Route"]

0        CCU→MAA
1        AMD→PNQ
2        CCU→DEL
3        AMD→HYD
4        HYD→PNQ
          ...
87268    MAA→AMD
87269    CCU→AMD
87270    AMD→PNQ
87271    MAA→PNQ
87272    BOM→MAA
Name: Route, Length: 87273, dtype: object

In [97]:
df.groupby("Airline")["Aircraft_Type"].agg(lambda x: x.value_counts().idxmax())

Airline
Air India     B737
GoAir         A320
IndiGo       ATR72
SpiceJet     ATR72
Vistara       B777
Name: Aircraft_Type, dtype: object

In [98]:
df.groupby("Route")["Delay_minutes"].mean().sort_values(ascending=False)

Route
MAA→DEL    29.051596
AMD→CCU    28.986091
BOM→CCU    28.735659
CCU→BOM    28.729113
DEL→BLR    28.538008
PNQ→CCU    28.450758
CCU→AMD    28.275989
DEL→MAA    28.147345
BLR→DEL    27.999774
CCU→PNQ    27.937419
CCU→BLR    27.828687
BLR→CCU    27.222526
AMD→MAA    25.921450
CCU→DEL    25.763351
DEL→CCU    25.487677
MAA→AMD    25.169874
BLR→AMD    24.929146
CCU→MAA    24.840109
MAA→CCU    24.414885
DEL→HYD    24.407235
HYD→DEL    23.979853
DEL→BOM    23.897140
HYD→CCU    23.771066
DEL→PNQ    23.722153
CCU→HYD    23.621392
BOM→DEL    23.517286
AMD→BLR    23.461898
PNQ→DEL    23.387801
MAA→BOM    22.589383
BOM→MAA    21.999562
HYD→AMD    21.913494
MAA→PNQ    21.462691
AMD→HYD    21.332748
BLR→BOM    21.099256
PNQ→MAA    20.870182
BOM→BLR    20.380513
AMD→DEL    19.946692
DEL→AMD    19.894977
BLR→PNQ    19.681791
PNQ→BLR    19.476216
HYD→BOM    18.944702
PNQ→HYD    18.628195
MAA→HYD    18.282930
HYD→BLR    18.270462
BOM→HYD    18.086455
BLR→HYD    17.993698
AMD→PNQ    17.843374
HYD→PNQ    17.764754
PNQ→AMD    17.603113
HYD→MAA    17.447880
AMD→BOM    17.425360
BOM→AMD    16.894296
MAA→BLR    16.700550
BLR→MAA    15.960545
PNQ→BOM    15.771545
BOM→PNQ    14.998061
Name: Delay_minutes, dtype: float64

In [99]:
df.groupby("Airline")["Delay_minutes"].agg(avg_delayed="mean",max_delay="max",delayed_percent=lambda x : (x>15).mean()*100)

           avg_delayed   max_delay  delayed_percent
Airline
Air India    22.384633  121.267409        56.265272
GoAir        22.624019  125.336608        56.670291
IndiGo       22.401305  119.967686        57.200322
SpiceJet     22.302662  125.612276        56.235281
Vistara      22.641319  125.383698        57.077967

In [100]:
df[df["Delay_minutes"]>df.groupby("Airline")["Delay_minutes"].transform("mean")]

,Flight_Number,Airline,Aircraft_Type,Origin,Destination,Date,Distance_km,Duration_hours,Ticket_Price,Fuel_Cost,Weather_Condition,Delay_minutes,Passenger_Count,Fuel_cost_per_km,Price_per_hour,Delayed_Flag,Month,Day,Route
1,5263,IndiGo,A320,AMD,PNQ,2023-09-21,519.0,NaN,2912.486246,1790.502002,Cloudy,27.908655,119,3.449908,NaN,True,9,21,AMD→PNQ
2,1877,GoAir,B737,CCU,DEL,2023-11-30,1423.0,2.112585,2177.869901,5122.704201,Cloudy,26.339672,122,3.599933,1030.902631,True,11,30,CCU→DEL
11,9397,Air India,A320,DEL,CCU,2023-03-15,1423.0,2.131190,3756.982406,4989.393836,Rainy,46.930670,123,3.506250,1762.856345,True,3,15,DEL→CCU
12,1289,Vistara,B777,CCU,PNQ,2023-04-21,1671.0,NaN,4959.089625,7032.822873,Rainy,61.485096,326,4.208751,NaN,True,4,21,CCU→PNQ
13,8434,IndiGo,B737,MAA,HYD,2023-08-22,516.0,1.013932,2924.485528,1879.675483,Foggy,72.198642,101,3.642782,2884.301931,True,8,22,MAA→HYD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87262,8736,SpiceJet,A321,HYD,CCU,2023-07-15,1238.0,1.981538,3244.475151,4543.515662,Clear,24.493061,204,3.670045,1637.352154,True,7,15,HYD→CCU
87264,7744,Air India,B737,PNQ,BOM,2023-03-08,124.0,0.618771,3361.177557,500.000000,Foggy,91.946013,90,4.032258,5432.021082,True,3,8,PNQ→BOM
87268,5730,GoAir,ATR72,MAA,AMD,2023-08-01,1395.0,3.140030,2322.841620,3849.760336,Foggy,38.650092,57,2.759685,739.751444,True,8,1,MAA→AMD
87271,2248,IndiGo,B777,MAA,PNQ,2023-07-17,933.0,1.425115,3542.425616,3908.780885,Rainy,27.970932,243,4.189476,2485.712197,True,7,17,MAA→PNQ
87272,6529,SpiceJet,ATR72,BOM,MAA,2023-05-23,1056.0,2.655092,2963.984721,2977.489964,Foggy,88.251829,65,2.819593,1116.339561,True,5,23,BOM→MAA

In [101]:
Q1= df["Ticket_Price"].quantile(0.25)
Q3= df["Ticket_Price"].quantile(0.75)
IQR = Q3-Q1
lower_limit = Q1-1.5*IQR
upper_limit= Q3+1.5*IQR
outliers = df[(df["Ticket_Price"]<lower_limit)|(df["Ticket_Price"]>upper_limit)]

In [102]:
outliers

,Flight_Number,Airline,Aircraft_Type,Origin,Destination,Date,Distance_km,Duration_hours,Ticket_Price,Fuel_Cost,Weather_Condition,Delay_minutes,Passenger_Count,Fuel_cost_per_km,Price_per_hour,Delayed_Flag,Month,Day,Route
6394,9209,Vistara,B777,DEL,CCU,2023-09-01,1423.0,2.021472,5368.171569,5959.879566,Cloudy,6.836280,312,4.188250,2655.575288,False,9,1,DEL→CCU
6699,1082,Vistara,A321,DEL,HYD,2023-07-29,1265.0,1.866418,5369.387265,4752.035732,Rainy,78.890195,159,3.756550,2876.841023,True,7,29,DEL→HYD
13993,4112,Vistara,B777,MAA,AMD,2023-01-27,1395.0,2.141470,5392.958224,5919.466608,Clear,0.000000,301,4.243345,2518.344400,False,1,27,MAA→AMD
14956,7611,Vistara,B777,HYD,DEL,2023-05-30,1265.0,NaN,5451.247796,5379.606508,Clear,19.608394,309,4.252653,NaN,True,5,30,HYD→DEL
21499,7466,Vistara,B777,DEL,PNQ,2023-06-01,1186.0,1.988319,5404.570101,5020.917900,Foggy,62.170081,299,4.233489,2718.160656,True,6,1,DEL→PNQ
46524,2931,Vistara,B777,BOM,CCU,2023-09-22,1762.0,NaN,5447.468186,7401.579033,Cloudy,35.427032,297,4.200669,NaN,True,9,22,BOM→CCU
48488,7315,Vistara,B777,BLR,AMD,2023-03-08,1247.0,1.908228,5421.028066,5275.995642,Clear,8.128374,297,4.230951,2840.870725,False,3,8,BLR→AMD
49961,4722,Vistara,B777,PNQ,CCU,2023-12-11,1671.0,2.641448,5419.160628,6980.227776,Clear,0.596940,330,4.177276,2051.587235,False,12,11,PNQ→CCU
50037,8410,Vistara,B777,DEL,HYD,2023-06-23,1265.0,1.900558,5472.952449,5282.028105,Cloudy,42.376033,317,4.175516,2879.655841,True,6,23,DEL→HYD
58312,4854,Vistara,B777,MAA,AMD,2023-01-06,1395.0,2.163003,5376.739111,6003.670299,Cloudy,29.189341,303,4.303706,2485.775499,True,1,6,MAA→AMD
71570,4556,Vistara,B777,DEL,MAA,2023-08-09,1769.0,2.388252,5422.996123,7423.081266,Cloudy,27.196052,235,4.196202,2270.696453,True,8,9,DEL→MAA
73438,4372,Vistara,A321,BLR,DEL,2023-07-23,1747.0,2.616201,5612.914951,6531.996057,Foggy,91.340445,161,3.738979,2145.444518,True,7,23,BLR→DEL
76702,2320,Vistara,A321,HYD,DEL,2023-06-06,1265.0,1.770765,5394.929064,4635.519860,Cloudy,8.025870,171,3.664443,3046.666118,False,6,6,HYD→DEL
80805,7228,Vistara,B777,DEL,BLR,2023-11-20,1747.0,2.646702,5388.461347,7305.232219,Cloudy,16.414698,297,4.181587,2035.915494,True,11,20,DEL→BLR
84374,5817,Vistara,A321,DEL,MAA,2023-02-12,1769.0,2.618421,5560.949164,6444.241627,Cloudy,21.386968,152,3.642873,2123.779367,True,2,12,DEL→MAA
86465,2345,Vistara,B777,DEL,BLR,2023-04-28,1747.0,2.579403,5380.256903,7304.895935,Rainy,38.290345,288,4.181394,2085.853375,True,4,28,DEL→BLR

In [103]:
route_stats= df.groupby("Route").agg(
    avg_delay=("Delay_minutes","mean"),
    avg_price=("Ticket_Price","mean"),
    avg_fuel=("Fuel_cost_per_km","mean"),
    flights = ("Route","count")
)

In [104]:
route_stats=route_stats[route_stats["flights"]>50]

In [105]:
worst_routes= route_stats.sort_values(["avg_delay","avg_price","avg_fuel"],ascending=[False,True,False])
worst_routes.head(2)

         avg_delay    avg_price  avg_fuel  flights
Route
MAA→DEL  29.051596  3519.981553  3.548759     1499
AMD→CCU  28.986091  3512.705916  3.559584     1503

In [106]:
costly_delay = df[df["Delay_minutes"]>20].groupby("Airline").size()

In [107]:
costly_delay.sort_values(ascending=False).head(1)

Airline
GoAir    8236
dtype: int64

In [108]:
df[df["Delay_minutes"]>20].groupby("Airline")["Passenger_Count"].sum().sort_values(ascending=False).head(1)

Airline
GoAir    1252252
Name: Passenger_Count, dtype: int64